K: 30
TeammateEncoder_num_heads: 4
act_dim: 5
alpha: 0.0001
batch_size: 4096
beta: 100
clip_value: 2
device: cuda
dt_activation_function: relu
dt_dropout: 0.3
dt_embed_dim: 64
dt_train_steps: 1
dt_weight_decay: 0.0001
embed_dim: 64
env: stag_hunt
gama: 100
goal_dim: 75
goal_steps: 3
lr: 0.01
max_ep_len: 201
model_save_path: models
n_head: 1
n_layer: 2
num_agents: 4
num_epochs: 100
save_dir: training_output/20250226_150058
save_interval: 2
sigma: 0.001
state_dim: 75
test_interval: 2
train_data_path: data/PP4a_wo_aug.pt
type: PP4a
warmup_steps: 10
weight_decay: 1.0e-05
