mac: "basic"
action_selector: epsilon_greedy
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
explore_alg: vdn
population_alg: vdn

agent: "rnn"
env_args: 
  layout_name: "forced_coordination_hard"
  dense_reward: true
  reset_when_success: false
