env: lbf
type: LBF
device: cuda
state_dim: 21
act_dim: 6
num_agents: 2
output_dim: 64
hidden_dim: 128
max_ep_len: 51
update_freq: 10

lr: 0.001
weight_decay: 0.0001
gamma: 0.98
beta: 15
batch_size: 131072
num_epochs: 100

train_data_path: data/LBF_episodes_datas_rtg.pt
test_interval: 2
save_interval: 10
device: "cuda"
