env: overcooked
type: overcooked
device: cuda
state_dim: 62
act_dim: 6
num_agents: 2
output_dim: 64
hidden_dim: 256
max_ep_len: 401
update_freq: 100

lr: 0.00001
weight_decay: 0.0001
gamma: 0.95
beta: 0.5
batch_size: 32768
num_epochs: 100

train_data_path: data/overcooked_episodes_datas_rtg_new.pt
test_interval: 2
save_interval: 10
device: "cuda"
