env: overcooked
type: overcooked
device: cuda
state_dim: 62
act_dim: 6
num_agents: 2
z_dim: 128
output_dim: 64
hidden_dim: 128
max_ep_len: 51
update_freq: 40

lr: 0.01
weight_decay: 0.001
gamma: 0.9  # 折扣因子
beta: 0.9   # a2c前的系数
alpha: 0.1  # policy_loss中log前的系数
sita: 0.1  # entropy前的系数
batch_size: 16384
num_epochs: 100

train_data_path: data/overcooked_episodes_datas_rtg_new.pt
test_interval: 2
save_interval: 10
device: "cuda"
