env: stag_hunt
type: PP4a

device: cuda
batch_size: 8192
lr: 0.00001
weight_decay: 0.00001
alpha: 0.0001   # 预测r的MSE的权重
beta: 100   # MIE第一项的权重
gama: 100   # MIE第二项的权重
sigma: 0.001 # goal部分的总权重
clip_value: 2
num_agents: 4
goal_steps: 2

# train_model function
num_epochs: 100
save_interval: 2
model_save_path: models
test_interval: 2

# network
state_dim: 75
embed_dim: 32
TeammateEncoder_num_heads: 4
goal_dim: 75
act_dim: 5
max_ep_len: 201

# DT
dt_embed_dim: 64
K: 15
n_layer: 3
n_head: 1
dt_activation_function: relu
dt_dropout: 0.1
warmup_steps: 10
dt_weight_decay: 0.0001
dt_lr: 0.01
dt_train_steps: 1

# train_data_path: data/PP4a_episodes_datas.pt
# train_data_path: data/PP4a_test_rtg.pt
train_data_path: data/PP4a_episodes_datas_rtg_new.pt