env: stag_hunt
type: PP4a
device: cuda
state_dim: 75
act_dim: 5
num_agents: 4
output_dim: 64
hidden_dim: 128
max_ep_len: 201
update_freq: 20

lr: 0.0001
weight_decay: 0.0001
gamma: 0.98
beta: 0.5
batch_size: 131072
num_epochs: 100

train_data_path: data/PP4a_episodes_datas_rtg_new.pt
test_interval: 2
save_interval: 10
device: "cuda"
